/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "E:\\elvis\\node_modules\\.pnpm\\@vuepress+core@1.9.9\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "E:\\elvis\\node_modules\\.pnpm\\@vuepress+plugin-active-header-links@1.9.9\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "E:\\elvis\\node_modules\\.pnpm\\@vuepress+plugin-medium-zoom@1.5.0\\node_modules\\@vuepress\\plugin-medium-zoom\\clientRootMixin.js"
import m3 from "E:\\elvis\\node_modules\\.pnpm\\@vuepress+plugin-nprogress@1.9.9\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m4 from "E:\\elvis\\node_modules\\.pnpm\\vuepress-plugin-smooth-scroll@0.0.9\\node_modules\\vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"
import m5 from "E:\\elvis\\node_modules\\.pnpm\\vuepress-plugin-code-copy@1.0.6\\node_modules\\vuepress-plugin-code-copy\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5
]