/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "elvisの博客",
  "description": "",
  "base": "/blog/",
  "headTags": [],
  "pages": [
    {
      "title": "博客首页",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2346e570",
      "path": "/",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "ECMAScript 7",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/7.html",
      "relativePath": "handbook/ECMAScript/7.md",
      "key": "v-5e9a004b",
      "path": "/handbook/ECMAScript/7.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Mac.html",
      "relativePath": "handbook/Electron/Mac.md",
      "key": "v-549460eb",
      "path": "/handbook/Electron/Mac.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "ECMAScript 6（ECMAScript 2015）",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/6.html",
      "relativePath": "handbook/ECMAScript/6.md",
      "key": "v-47fc5f6b",
      "path": "/handbook/ECMAScript/6.html",
      "headers": [
        {
          "level": 2,
          "title": "let 和 const 关键字",
          "slug": "let-和-const-关键字"
        },
        {
          "level": 2,
          "title": "箭头函数",
          "slug": "箭头函数"
        },
        {
          "level": 2,
          "title": "模板字符串",
          "slug": "模板字符串"
        },
        {
          "level": 2,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 2,
          "title": "类和继承",
          "slug": "类和继承"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 2,
          "title": "模块化",
          "slug": "模块化"
        },
        {
          "level": 2,
          "title": "剩余参数和展开运算符",
          "slug": "剩余参数和展开运算符"
        },
        {
          "level": 2,
          "title": "Map 和 Set",
          "slug": "map-和-set"
        }
      ],
      "lastUpdated": "2023/8/10 11:16:50",
      "lastUpdatedTimestamp": 1691637410000
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Windows.html",
      "relativePath": "handbook/Electron/Windows.md",
      "key": "v-513b92eb",
      "path": "/handbook/Electron/Windows.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "ECMAScript 5",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/5.html",
      "relativePath": "handbook/ECMAScript/5.md",
      "key": "v-315ebe8b",
      "path": "/handbook/ECMAScript/5.html",
      "headers": [
        {
          "level": 2,
          "title": "保护对象",
          "slug": "保护对象"
        },
        {
          "level": 2,
          "title": "保护对象的结构",
          "slug": "保护对象的结构"
        },
        {
          "level": 2,
          "title": "替换this指向",
          "slug": "替换this指向"
        },
        {
          "level": 2,
          "title": "Es5新增的数组方法",
          "slug": "es5新增的数组方法"
        }
      ],
      "lastUpdated": "2023/8/10 11:16:50",
      "lastUpdatedTimestamp": 1691637410000
    },
    {
      "title": "通用规则",
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Base.html",
      "relativePath": "handbook/Electron/Base.md",
      "key": "v-6d93a82e",
      "path": "/handbook/Electron/Base.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "ECMAScript 8",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/8.html",
      "relativePath": "handbook/ECMAScript/8.md",
      "key": "v-7537a12b",
      "path": "/handbook/ECMAScript/8.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "常用指令",
      "frontmatter": {},
      "regularPath": "/handbook/Git/Common.html",
      "relativePath": "handbook/Git/Common.md",
      "key": "v-1d6cc665",
      "path": "/handbook/Git/Common.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "事件队列",
      "frontmatter": {},
      "regularPath": "/handbook/JavaScript/eventloop.html",
      "relativePath": "handbook/JavaScript/eventloop.md",
      "key": "v-716a876b",
      "path": "/handbook/JavaScript/eventloop.html",
      "lastUpdated": "2023/8/9 17:04:05",
      "lastUpdatedTimestamp": 1691571845000
    },
    {
      "title": "基础优化",
      "frontmatter": {},
      "regularPath": "/handbook/PowerOptimize/Base.html",
      "relativePath": "handbook/PowerOptimize/Base.md",
      "key": "v-5603a465",
      "path": "/handbook/PowerOptimize/Base.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "基础使用",
      "frontmatter": {},
      "regularPath": "/handbook/Node/Base.html",
      "relativePath": "handbook/Node/Base.md",
      "key": "v-10f0e129",
      "path": "/handbook/Node/Base.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "继承",
      "frontmatter": {},
      "regularPath": "/handbook/JavaScript/extend.html",
      "relativePath": "handbook/JavaScript/extend.md",
      "key": "v-ac1b0326",
      "path": "/handbook/JavaScript/extend.html",
      "headers": [
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "一、原型链继承",
          "slug": "一、原型链继承"
        },
        {
          "level": 3,
          "title": "一、借用构造函数继承",
          "slug": "一、借用构造函数继承"
        },
        {
          "level": 3,
          "title": "三、组合使用原型链和构造函数继承",
          "slug": "三、组合使用原型链和构造函数继承"
        },
        {
          "level": 3,
          "title": "四、原型式继承",
          "slug": "四、原型式继承"
        },
        {
          "level": 3,
          "title": "五、寄生式继承",
          "slug": "五、寄生式继承"
        },
        {
          "level": 3,
          "title": "六、寄生组合式继承",
          "slug": "六、寄生组合式继承"
        }
      ],
      "lastUpdated": "2023/8/9 17:04:05",
      "lastUpdatedTimestamp": 1691571845000
    },
    {
      "title": "React 17",
      "frontmatter": {},
      "regularPath": "/handbook/React/17.html",
      "relativePath": "handbook/React/17.md",
      "key": "v-5afbefb6",
      "path": "/handbook/React/17.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "Vue2",
      "frontmatter": {},
      "regularPath": "/handbook/Vue/2.html",
      "relativePath": "handbook/Vue/2.md",
      "key": "v-f8a0bfe6",
      "path": "/handbook/Vue/2.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "基础类型",
      "frontmatter": {},
      "regularPath": "/handbook/TypeScript/BaseType.html",
      "relativePath": "handbook/TypeScript/BaseType.md",
      "key": "v-e1b0248a",
      "path": "/handbook/TypeScript/BaseType.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "基础配置",
      "frontmatter": {},
      "regularPath": "/handbook/Webpack/Base.html",
      "relativePath": "handbook/Webpack/Base.md",
      "key": "v-4ecc7345",
      "path": "/handbook/Webpack/Base.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "title": "Vue3",
      "frontmatter": {},
      "regularPath": "/handbook/Vue/3.html",
      "relativePath": "handbook/Vue/3.md",
      "key": "v-fd33f0ea",
      "path": "/handbook/Vue/3.html",
      "lastUpdated": "2023/8/9 10:30:58",
      "lastUpdatedTimestamp": 1691548258000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Github",
        "link": "https://github.com/elvis-shiqi"
      }
    ],
    "sidebar": [
      {
        "title": "JavaScript",
        "collapsable": true,
        "children": [
          {
            "title": "继承",
            "path": "/handbook/JavaScript/extend"
          },
          {
            "title": "事件循环及事件队列",
            "path": "/handbook/JavaScript/eventloop"
          }
        ]
      },
      {
        "title": "ECMAScript规范及特性",
        "collapsable": true,
        "children": [
          {
            "title": "ECMAScript5特性",
            "path": "/handbook/ECMAScript/5"
          },
          {
            "title": "ECMAScript6特性",
            "path": "/handbook/ECMAScript/6"
          }
        ]
      },
      {
        "title": "TypeScript",
        "collapsable": true,
        "children": [
          {
            "title": "基础类型",
            "path": "/handbook/TypeScript/BaseType"
          }
        ]
      },
      {
        "title": "Vue",
        "collapsable": true,
        "children": [
          {
            "title": "Vue2",
            "path": "/handbook/Vue/2"
          },
          {
            "title": "Vue3",
            "path": "/handbook/Vue/3"
          }
        ]
      },
      {
        "title": "React",
        "collapsable": true,
        "children": [
          {
            "title": "React 17",
            "path": "/handbook/React/17"
          }
        ]
      },
      {
        "title": "Webpack",
        "collapsable": true,
        "children": [
          {
            "title": "基础配置",
            "path": "/handbook/Webpack/Base"
          }
        ]
      },
      {
        "title": "性能优化",
        "collapsable": true,
        "children": [
          {
            "title": "基础优化",
            "path": "/handbook/PowerOptimize/Base"
          }
        ]
      },
      {
        "title": "Git",
        "collapsable": true,
        "children": [
          {
            "title": "常用指令",
            "path": "/handbook/Git/Common"
          }
        ]
      },
      {
        "title": "Node",
        "collapsable": true,
        "children": [
          {
            "title": "基础使用",
            "path": "/handbook/Node/Base"
          }
        ]
      },
      {
        "title": "Electron",
        "collapsable": true,
        "children": [
          {
            "title": "通用规则",
            "path": "/handbook/Electron/Base"
          },
          {
            "title": "Windows",
            "path": "/handbook/Electron/Windows"
          },
          {
            "title": "Mac",
            "path": "/handbook/Electron/Mac"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}