/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "elvisの博客",
  "description": "",
  "base": "/learn-record/",
  "headTags": [],
  "pages": [
    {
      "title": "ECMAScript 7",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/7.html",
      "relativePath": "handbook/ECMAScript/7.md",
      "key": "v-8c701c94",
      "path": "/handbook/ECMAScript/7.html"
    },
    {
      "title": "博客首页",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-632698b6",
      "path": "/"
    },
    {
      "title": "ECMAScript 6",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/6.html",
      "relativePath": "handbook/ECMAScript/6.md",
      "key": "v-b9ab5e54",
      "path": "/handbook/ECMAScript/6.html"
    },
    {
      "title": "通用规则",
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Base.html",
      "relativePath": "handbook/Electron/Base.md",
      "key": "v-10ad6e94",
      "path": "/handbook/Electron/Base.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Mac.html",
      "relativePath": "handbook/Electron/Mac.md",
      "key": "v-a07b5b54",
      "path": "/handbook/Electron/Mac.html"
    },
    {
      "title": "常用指令",
      "frontmatter": {},
      "regularPath": "/handbook/Git/Common.html",
      "relativePath": "handbook/Git/Common.md",
      "key": "v-d4ebb560",
      "path": "/handbook/Git/Common.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/Electron/Windows.html",
      "relativePath": "handbook/Electron/Windows.md",
      "key": "v-d6fa2d54",
      "path": "/handbook/Electron/Windows.html"
    },
    {
      "title": "基础优化",
      "frontmatter": {},
      "regularPath": "/handbook/PowerOptimize/Base.html",
      "relativePath": "handbook/PowerOptimize/Base.md",
      "key": "v-5f93cd50",
      "path": "/handbook/PowerOptimize/Base.html"
    },
    {
      "title": "React 17",
      "frontmatter": {},
      "regularPath": "/handbook/React/17.html",
      "relativePath": "handbook/React/17.md",
      "key": "v-17619490",
      "path": "/handbook/React/17.html"
    },
    {
      "title": "ECMAScript 8",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/8.html",
      "relativePath": "handbook/ECMAScript/8.md",
      "key": "v-5f34dad4",
      "path": "/handbook/ECMAScript/8.html"
    },
    {
      "title": "基础使用",
      "frontmatter": {},
      "regularPath": "/handbook/Node/Base.html",
      "relativePath": "handbook/Node/Base.md",
      "key": "v-c7c20258",
      "path": "/handbook/Node/Base.html"
    },
    {
      "title": "基础类型",
      "frontmatter": {},
      "regularPath": "/handbook/TypeScript/BaseType.html",
      "relativePath": "handbook/TypeScript/BaseType.md",
      "key": "v-755187e6",
      "path": "/handbook/TypeScript/BaseType.html"
    },
    {
      "title": "Vue3",
      "frontmatter": {},
      "regularPath": "/handbook/Vue/3.html",
      "relativePath": "handbook/Vue/3.md",
      "key": "v-16560036",
      "path": "/handbook/Vue/3.html"
    },
    {
      "title": "基础配置",
      "frontmatter": {},
      "regularPath": "/handbook/Webpack/Base.html",
      "relativePath": "handbook/Webpack/Base.md",
      "key": "v-ac0b36a0",
      "path": "/handbook/Webpack/Base.html"
    },
    {
      "title": "Vue2",
      "frontmatter": {},
      "regularPath": "/handbook/Vue/2.html",
      "relativePath": "handbook/Vue/2.md",
      "key": "v-189f98b8",
      "path": "/handbook/Vue/2.html"
    },
    {
      "title": "ECMAScript 5",
      "frontmatter": {},
      "regularPath": "/handbook/ECMAScript/5.html",
      "relativePath": "handbook/ECMAScript/5.md",
      "key": "v-e6e6a014",
      "path": "/handbook/ECMAScript/5.html",
      "headers": [
        {
          "level": 2,
          "title": "支持ES5的浏览器",
          "slug": "支持es5的浏览器"
        },
        {
          "level": 2,
          "title": "DOM文档加载的步骤为",
          "slug": "dom文档加载的步骤为"
        },
        {
          "level": 2,
          "title": "readystatechange事件",
          "slug": "readystatechange事件"
        },
        {
          "level": 2,
          "title": "DOMContentLoaded事件",
          "slug": "domcontentloaded事件"
        },
        {
          "level": 2,
          "title": "ES5的严格模式",
          "slug": "es5的严格模式"
        },
        {
          "level": 3,
          "title": "为什么要用严格模式",
          "slug": "为什么要用严格模式"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "JSON对象方法",
          "slug": "json对象方法"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Github",
        "link": "https://github.com/elvis-shiqi"
      }
    ],
    "sidebar": [
      {
        "title": "ECMAScript规范及特性",
        "collapsable": true,
        "children": [
          {
            "title": "ECMAScript5",
            "path": "/handbook/ECMAScript/5"
          },
          {
            "title": "ECMAScript6",
            "path": "/handbook/ECMAScript/6"
          },
          {
            "title": "ECMAScript7",
            "path": "/handbook/ECMAScript/7"
          },
          {
            "title": "ECMAScript8",
            "path": "/handbook/ECMAScript/8"
          }
        ]
      },
      {
        "title": "TypeScript",
        "collapsable": true,
        "children": [
          {
            "title": "基础类型",
            "path": "/handbook/TypeScript/BaseType"
          }
        ]
      },
      {
        "title": "Vue",
        "collapsable": true,
        "children": [
          {
            "title": "Vue2",
            "path": "/handbook/Vue/2"
          },
          {
            "title": "Vue3",
            "path": "/handbook/Vue/3"
          }
        ]
      },
      {
        "title": "React",
        "collapsable": true,
        "children": [
          {
            "title": "React 17",
            "path": "/handbook/React/17"
          }
        ]
      },
      {
        "title": "Webpack",
        "collapsable": true,
        "children": [
          {
            "title": "基础配置",
            "path": "/handbook/Webpack/Base"
          }
        ]
      },
      {
        "title": "性能优化",
        "collapsable": true,
        "children": [
          {
            "title": "基础优化",
            "path": "/handbook/PowerOptimize/Base"
          }
        ]
      },
      {
        "title": "Git",
        "collapsable": true,
        "children": [
          {
            "title": "常用指令",
            "path": "/handbook/Git/Common"
          }
        ]
      },
      {
        "title": "Node",
        "collapsable": true,
        "children": [
          {
            "title": "基础使用",
            "path": "/handbook/Node/Base"
          }
        ]
      },
      {
        "title": "Electron",
        "collapsable": true,
        "children": [
          {
            "title": "通用规则",
            "path": "/handbook/Electron/Base"
          },
          {
            "title": "Windows",
            "path": "/handbook/Electron/Windows"
          },
          {
            "title": "Mac",
            "path": "/handbook/Electron/Mac"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}